# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fiche_oeuvre.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets
import os


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1138, 805)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("background-color : qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(110, 66, 255,255), stop:1 rgba(255, 120, 174,100))")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet(
			"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(110, 66, 255,255), stop:1 rgba(255, 120, 174,100));"
		)

        self.centralwidget.setObjectName("centralwidget")
        self.couverture = QtWidgets.QLabel(self.centralwidget)
        self.couverture.setGeometry(QtCore.QRect(50, 160, 281, 381))
        self.couverture.setText("")
        self.couverture.setObjectName("couverture")
        
        self.titre = QtWidgets.QLabel(self.centralwidget)
        self.titre.setGeometry(QtCore.QRect(380, 180, 241, 31))
        self.titre.setText("")
        self.titre.setObjectName("titre")
        
        self.date = QtWidgets.QLabel(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(400, 220, 91, 21))
        self.date.setText("")
        
        self.date.setObjectName("date")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setGeometry(QtCore.QRect(380, 350, 91, 31))
        self.textBrowser.setMouseTracking(True)
        self.textBrowser.setAcceptDrops(True)
        self.textBrowser.setObjectName("textBrowser")
        
        self.score_evaluation = QtWidgets.QLabel(self.centralwidget)
        self.score_evaluation.setGeometry(QtCore.QRect(530, 260, 81, 21))
        self.score_evaluation.setText("")
        self.score_evaluation.setObjectName("score_evaluation")
        
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(380, 260, 131, 21))
        self.textBrowser_2.setObjectName("textBrowser_2")
        
        self.description = QtWidgets.QLabel(self.centralwidget)
        self.description.setGeometry(QtCore.QRect(380, 390, 341, 141))
        self.description.setText("")
        self.description.setObjectName("description")
        
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(800, 210, 291, 351))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(890, 160, 81, 31))
        self.textBrowser_3.setObjectName("textBrowser_3")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1138, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.875pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Description</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.875pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Score d\'évaluation :</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.875pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Mots-clés</span></p></body></html>"))


class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

        # Charger une œuvre spécifique par son ID 
			# Test 
        oeuvre_id = 1
        self.afficher_infos_oeuvre(oeuvre_id)

    def recuperer_infos_oeuvre(self, oeuvre_id):
        """Récupère les informations d'une œuvre depuis la base de données."""
        conn = sqlite3.connect('../database/culturama.db')  
        cursor = conn.cursor()
        cursor.execute("SELECT nom, date, description, score_evaluation, mots_cles FROM oeuvre WHERE id=?", (oeuvre_id,))
        row = cursor.fetchone()
        conn.close()
        
        return {
            'nom': row[0],
            'date': row[1],
            'description': row[2],
            'score_evaluation': row[3],
            'mots_cles': row[4]
        }

    def afficher_infos_oeuvre(self, oeuvre_id):
        """Charge et affiche les informations d'une œuvre spécifique."""
        oeuvre = self.recuperer_infos_oeuvre(oeuvre_id)
        self.titre.setText(oeuvre['nom'])
        self.date.setText(oeuvre['date'])
        self.description.setText(oeuvre['description'])
        self.score_evaluation.setText(str(oeuvre['score_evaluation']))
        # Charge  l'image de couverture depuis le dossier Cache
        
        image_path = os.path.join("..","Cache", f"{oeuvre_id}.jpg")  
        if os.path.exists(image_path):
            pixmap = QtGui.QPixmap(image_path)
            self.couverture.setPixmap(pixmap)
            self.couverture.setScaledContents(True)
        else:
            print("L'image de couverture n'a pas été trouvée.")
            
        self.ajouter_mots_cles(oeuvre['mots_cles'])

    def ajouter_mots_cles(self, mots_cles):
        mots = mots_cles.split(", ")
        row, col = 0, 0

        for i in reversed(range(self.gridLayout.count())):
            self.gridLayout.itemAt(i).widget().setParent(None)

        for mot in mots:
            label = QtWidgets.QLabel(mot)
            label.setStyleSheet("background-color: rgba(255, 255, 255, 150); padding: 5px; border-radius: 5px;")
            self.gridLayout.addWidget(label, row, col)
            col += 1
            if col >= 3:
                col = 0
                row += 1

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())
